env:
  contexts:
  - name: http://localhost:8001
    urls:
    - http://localhost:8001
    includePaths:
    - http://localhost:8001.*
    authentication:
      verification:
        method: response
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: cookie
    technology: {}
    structure: {}
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: import
  parameters:
    type: har
    fileName: /root/AwesomeToDo/tmp/localhost_Archive.har
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters:
    context: http://localhost:8001
  policyDefinition:
    defaultStrength: low
    defaultThreshold: "off"
- type: report
  parameters:
    template: modern
    theme: corporate
    reportDir: /root
    reportFile: zap_report.html
    reportTitle: ZAP Scanning Report
  risks:
  - info
  - low
  - medium
  - high
  confidences:
  - falsepositive
  - low
  - medium
  - high
  - confirmed
  sections:
  - passingrules
  - instancecount
  - alertdetails
  - alertcount
  - params
  - chart
  - statistics

